version: "3.3"
services:
  test:
    image: sale_ranking_server:test
    restart: on-failure
    ports:
    - 5001:5000
    environment:
      - SERVER_MODE=prod
      - DB_SALE_HOST=db
      - DB_SALE_USERNAME=root
      - DB_SALE_PASSWORD=mis@Pass01
      - DB_SALE_NAME=ratingscoring_test1
      - DB_QUOTATION_HOST=203.154.135.51
      - DB_QUOTATION_USERNAME=root
      - DB_QUOTATION_PASSWORD=118E84FDC1207D817492A
      - DB_QUOTATION_NAME=quatation
      - DB_QUOTATION_PORT=3313
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RECAPTCHA_SECRET=6Ldu3uIUAAAAAOeTaPJBXjgfPqVaK74pKxOdZcGy
      - ATTENDANT_TOKEN=DVIdkD7Bg/Gc8z1+O9tcAup44PMHbX1JxQYOLDiyRD4xd9m+IsEW8QoafTzPXWw5Dw==
      - ATTENDANT_TOKEN_TYPE=Bearer

